
CCFLAGS  =

# DO NOT CHANGE
ALL_CCFLAGS = -O -Wall $(CCFLAGS)
IINC     = -I..
LLIB     = -L../..

.cc.o:   ; sh ../../s++.sh $(ALL_CCFLAGS) $(IINC) -c $*.cc

all::	01_opeEqu_sample      02_opePlusEqu_sample     03_opePlusEqu_sample     04_opeElem_sample   05_length_sample
	06_cstrarray_sample   07_cstr_sample           08_at_sample             09_init_sample      10_resize_sample
	11_clean_sample       12_split_sample          13_assign_sample         14_assign_sample    15_put_sample
	16_put_sample         17_append_sample         18_append_sample         19_insert_sample    20_insert_sample
	21_replace_sample     22_replace_sample        23_erase_sample          24_swap_sample      25_copy_sample

01_opeEqu_sample:	01_opeEqu_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

02_opePlusEqu_sample:	02_opePlusEqu_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

03_opePlusEqu_sample:	03_opePlusEqu_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

04_opeElem_sample:	04_opeElem_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

05_length_sample:	05_length_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

06_cstrarray_sample:	06_cstrarray_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

07_cstr_sample:		07_cstr_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

08_at_sample:		08_at_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

09_init_sample:	09_init_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

10_resize_sample:	10_resize_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

11_clean_sample:	11_clean_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

12_split_sample:	12_split_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

13_assign_sample:	13_assign_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

14_assign_sample:	14_assign_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

15_put_sample:		15_put_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

16_put_sample:		16_put_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

17_append_sample:	17_append_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

18_append_sample:	18_append_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

19_insert_sample:	19_insert_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

20_insert_sample:	20_insert_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

21_replace_sample:	21_replace_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

22_replace_sample:	22_replace_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

23_erase_sample:	23_erase_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

24_swap_sample:		24_swap_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a

25_copy_sample:		25_copy_sample.o
	sh ../../s++.sh $(CPPC) $(LLIB) -o $@ $@.o ../../libslib.a


clean::
	rm -f *.o *.exe 01_opeEqu_sample      02_opePlusEqu_sample     03_opePlusEqu_sample     04_opeElem_sample   05_length_sample
			06_cstrarray_sample   07_cstr_sample           08_at_sample             09_init_sample      10_resize_sample 
			11_clean_sample       12_split_sample          13_assign_sample         14_assign_sample    15_put_sample
			16_put_sample         17_append_sample         18_append_sample         19_insert_sample    20_insert_sample
			21_replace_sample     22_replace_sample        23_erase_sample          24_swap_sample      25_copy_sample
