
clean::
	rm -f s_byteswap16 s_byteswap2 s_byteswap4 s_byteswap8 \
	      s_cvt_i16tod s_memfill s_memflip s_memmove s_memset s_memswap \
	      s_byteswap_cpy_test s_byteswap_test s_memcpy_test \
	      s_memfill_test s_memflip_test s_memmove_test \
	      s_memset_test s_memswap_test

